### ISSUE TITLE
AsyncResut CE cannot bind Result<,> type since 1.4.1

### ISSUE THREAD

**Issue by MaxDeg** [demystifyfp/FsToolkit.ErrorHandling#89]
Sadly since the version 1.4.1 the following code refuse to compile.

```fsharp
let getRepositorySettings apiKey (repository: Result<{| projectPermissions: ProjectPermissions; slug: string |}, AppError>) =
    asyncResult {
        let! repository = repository
        let! branches = BitbucketApi.branches apiKey repository.projectPermissions.project repository.slug
        let! prSettings = BitbucketApi.pullRequestSettings apiKey repository.projectPermissions.project repository.slug
        let! defaultReviewers = BitbucketApi.defaultReviewers apiKey repository.projectPermissions.project repository.slug
        let! masterRestrictions = BitbucketApi.masterBranchRestrictions apiKey repository.projectPermissions.project repository.slug
        let! permissionGroups = BitbucketApi.repositoryPermissionGroups apiKey repository.projectPermissions.project repository.slug

        return { project = repository.projectPermissions.project
                    repositorySlug = repository.slug
                    branches = branches
                    pullRequestSettings = prSettings
                    defaultReviewers = defaultReviewers
                    masterBranchRestrictions = masterRestrictions
                    permissionGroups = PermissionGroups.union repository.projectPermissions.permissionGroups permissionGroups }
    }
```

The following line is the responsible
`let! repository = repository`

It looks like the Bind method accepting a Bind has been removed for some reason.

**Comment by ursenzler** [comment]
I found the same issue.

Here a shorter repro code that compiles under 1.4.0 and fails under 1.4.1:

``` F#
module V141

open System
open FsToolkit.ErrorHandling

type Id = Id of Guid

type A = { Id : Id }
type B = { Id : Id }

let test () =
    asyncResult {
        let option = async { return Some { A.Id = Guid.NewGuid() |> Id } }
        let! result = option |> AsyncResult.requireSome "none"
        return { B.Id = result.Id }
    }
```

Error message:
0>C:\Projects\FsToolkit.Errorhandling.AsyncResultRepro\V141\Library.fs(14,9): Error FS0041 : No overloads match for method 'Bind'. The available overloads are shown below.
0>------- Finished building project: V141. Succeeded: False. Errors: 1. Warnings: 0

btw: many thanks for this awesome library!

**Comment by TheAngryByrd** [comment]
@MaxDeg may be related to #88 


---

@ursenzler 

Unfortunately I can't seem reproduce this.  It seems to compile fine with 1.4.0 and 1.4.1 for me. https://github.com/TheAngryByrd/fstk_issue89

**Comment by MaxDeg** [comment]
@TheAngryByrd indeed it's the same issue. I missed it :(

**Comment by TheAngryByrd** [comment]
No worries, I don't expect everyone to have the same intimate knowledge about all open issues :)

**Comment by TheAngryByrd** [comment]
@ursenzler nope I'm wrong.  VSCode was doing it's fun thing and not saving files.  :(

**Comment by TheAngryByrd** [comment]
Yeah this is exactly the same problem as #88.  Please take a look at https://github.com/demystifyfp/FsToolkit.ErrorHandling/issues/88#issuecomment-649718087 and comment on which solution seems best for you.

Closing as duplicate and moving conversation there.
