### ISSUE TITLE
>=1.3.0 causes nonsensical Intellisense/compilation errors (due to applicatives?)

### ISSUE THREAD

**Issue by cmeeren** [demystifyfp/FsToolkit.ErrorHandling#84]
After upgrading from 1.2.6 to 1.3.0 or above, I get nonsensical compilation errors:

![image](https://user-images.githubusercontent.com/7766733/84013556-5dea6200-a979-11ea-8e1b-64d74c3876ac.png)

I guess this has to do with applicatives.

I am using `<LangVersion>preview</LangVersion>` to get access to `nameof`, which I use extensively in logging.

It builds fine with the VSBuild task on Azure Pipelines, but locally there's nothing that can make it compile except downgrading to 1.2.6.

Note that I am not even using `and!`; the error come just from upgrading FsToolkit.ErrorHandling.

The errors can often be "fixed" by reordering the bang operator lines if possible, but that's not always possible nor desirable. For example like the below (which can't be used due to incorrect behavior):

![image](https://user-images.githubusercontent.com/7766733/84013766-a6a21b00-a979-11ea-97bb-d2f28ae417ea.png)

**Comment by TheAngryByrd** [comment]
This unfortunately feels like an F# compiler issue. :(

@baronfel and I are looking at making a PR to FSharp.Core soon.

**Comment by TheAngryByrd** [comment]
For a workaround right now could you do:

```fsharp
let! _ = finalizeUpdate user
```

---

@cartermp I think we found another edge case in CEs wrt applicatives.

**Comment by cmeeren** [comment]
> For a workaround right now could you do:
> 
> ```fsharp
> let! _ = finalizeUpdate user
> ```

Thanks for the tip. I'll stick with 1.2.6 for now; it's the most non-intrusive solution.

**Comment by TheAngryByrd** [comment]
I can definitely confirm this bug happens when adding the `BindReturn` member.

**Comment by baronfel** [comment]
@cartermp I'm about to submit an issue with more details that should help narrow it down

**Comment by TheAngryByrd** [comment]
I'm going to keep this open until F# release a new preview with the fix

**Comment by TheAngryByrd** [comment]
Pretty sure this is fixed in F# 5.0

**Comment by cmeeren** [comment]
Was fixed in an updated VS version, to be specific.
